### ISSUE TITLE
Consider deleting this project

### ISSUE THREAD

**Issue by hawkeyetwolf** [components/jquery_ns_autogrow#1]
Rather than maintain a fork, consider just adding instructions to [kalamuna/autogrow_textarea](https://github.com/kalamuna/autogrow_textarea)'s README. All people have to do is add a "repository" entry that provides the necessary "drupal-library" type definition.

Here's an example `repositories` section from our `drupal-project` fork (note the "chosen" entry):
```
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "chosen": {
            "type": "package",
            "package": {
                "name": "harvesthq/chosen",
                "version": "1.8.2",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/harvesthq/chosen/releases/download/v1.8.2/chosen_v1.8.2.zip",
                    "type": "zip"
                },
                "require": {
                    "composer/installers": "~1.2.0"
                }
            }
        }
    },
```

**Comment by RobLoach** [comment]
Moving the repo over to https://github.com/components ... Having native Composer support saves having to add the repository definition yourself, which is nice.

**Comment by hawkeyetwolf** [comment]
@RobLoach, the only issue with moving this repo to "Components" is that it now has a dependency on `components/jquery`. And if we make all Composer packages of type "component" land in the `/libraries` directory like we talked about, then we'd end up with a superfluous copy of jQuery sitting around unused in our Drupal projects' libraries folder, which I don't like.

What do you think? Should we just maintain a separate fork specific to Drupal?

**Comment by RobLoach** [comment]
Make `component`s install to /libraries at https://github.com/drupal-composer/drupal-project/pull/319 ...

Can add that in our own fork too https://github.com/kalamuna/drupal-project/pull/46

**Comment by hawkeyetwolf** [comment]
One other issue with using this as a proper "component" via [RobLoach/component-installer](https://github.com/RobLoach/component-installer) is that the JS gets moved from the expected location into js/css subdirectories. Also, the component-installer adds RequireJS stuff. I noticed this when trying to leverage [drmonty/chosen](https://github.com/drmonty/chosen).

**Comment by RobLoach** [comment]
@derekderaps Which project is installing component-installer? We likely don't need it with the `type:` definition.

**Comment by hawkeyetwolf** [comment]
It was [drmonty/chosen](https://github.com/drmonty/chosen), but now that we have our own shim repo for Chosen, this shouldn't be a problem anymore. Thanks! :)

**Comment by RobLoach** [comment]
:wave: :smile:
